# fly.toml app configuration file for bandboxbackend

app = 'bandboxbackend'
primary_region = 'bom'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = '/bin/bash -c "python manage.py migrate --noinput"'
  max_parallel = 1
  override_entrypoint = true

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
