app = "bandboxbackend"
console_command = "/code/manage.py shell"
primary_region = "bom"

[deploy]
release_command = "python manage.py migrate --noinput"

[env]
PORT = "8000"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8000
min_machines_running = 0
processes = ["app"]

[[statics]]
guest_path = "/code/static"
url_prefix = "/static/"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
