# Generated by Django 5.1.2 on 2025-10-08 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="slip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slip_no", models.IntegerField()),
                ("date", models.DateField()),
                ("due_date", models.DateField()),
                ("address", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=10)),
                ("amount", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=50)),
                ("service", models.CharField(max_length=50)),
                ("quantity", models.IntegerField()),
                ("price_per_unit", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "slip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="bills.slip",
                    ),
                ),
            ],
        ),
    ]
