# Generated by Django 5.1.2 on 2025-10-15 04:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WhatsAppConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("message_count", models.IntegerField(default=0)),
                ("unread_count", models.IntegerField(default=0)),
                (
                    "customer_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "wamid",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("from_number", models.CharField(db_index=True, max_length=20)),
                ("from_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("document", "Document"),
                            ("location", "Location"),
                            ("contacts", "Contacts"),
                            ("interactive", "Interactive"),
                            ("unknown", "Unknown"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("text_body", models.TextField(blank=True, null=True)),
                ("media_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "media_mime_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("media_url", models.URLField(blank=True, null=True)),
                ("media_caption", models.TextField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "location_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("location_address", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("read", "Read"),
                            ("replied", "Replied"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("raw_payload", models.JSONField(blank=True, null=True)),
                (
                    "context_message_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="whatsapp_wh_timesta_b98d29_idx"
                    ),
                    models.Index(
                        fields=["from_number", "-timestamp"],
                        name="whatsapp_wh_from_nu_4fe7be_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessageStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(db_index=True, max_length=255)),
                ("recipient_number", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("error_code", models.CharField(blank=True, max_length=50, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("raw_payload", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["message_id", "-timestamp"],
                        name="whatsapp_wh_message_f19858_idx",
                    )
                ],
            },
        ),
    ]
